name: containerbuildfedora30

on: [pull_request]

jobs:
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ 'fedora:30']

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        dnf install -y python3-pip
        dnf install -y python3-devel gcc
        pip3 install -r requirements.txt --ignore-installed
        pip3 install .[test] --ignore-installed
    - name: Lint with flake8
      run: |
        pip3 install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
