name: "Testing container matrix centos"

on: [push]

jobs:
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:8', 'fedora:30', 'fedora:31' ]
    steps:
    - uses: actions/checkout@v2
    - run: cat /etc/os-release
    - name: running a shell script file
      run: |
        chmod +x ./runtests.sh
        ./runtests.sh
    - run: |
        yum install -y epel-release;
        yum install -y python3-pip;
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install .[test]
        pip3 install zipp>=0.5
    - name: Lint with flake8
      run: |
        pip3 install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 --exclude=\.eggs,tests,docs,config/Dockerfiles --ignore=E124,E303,W504 --max-line-length 80 .
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $(which python) setup.py test

#jobs:
#  build:

#    runs-on: ubuntu-latest
#    container: centos:7

#    steps:
#    - uses: actions/checkout@v1
#    - name: Build
#      run: pip install -r requirements.txt
