name: "Testing container matrix centos"

on: [push]

jobs:
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [ 'centos:7', 'centos:8' ]
    steps:
    - run: cat /etc/centos-release

#jobs:
#  build:

#    runs-on: ubuntu-latest
#    container: centos:7

#    steps:
#    - uses: actions/checkout@v1
#    - name: Build
#      run: pip install -r requirements.txt
