name: "CI: autotools: clang 9"

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: pip install -r requirements.txt
