name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: 8000

    steps:
    - uses: actions/checkout@v1
    - name: Build check images available
      run: docker images
    - name: Pull image 
      run: sudo docker pull centos:8
    - name: Check running containers
      run: docker ps -a
    - name: Check images pulled
      run: docker images
