name: Docker Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PORT: 8000

    steps:
    - uses: actions/checkout@v1
    - name: Build check images available
      run: docker images
    - name: Pull image 
      run: sudo docker pull centos:8
    - name: Run a container
      run: docker run -d --privileged --name libvirt_disco centos:8 tail -f /dev/null
    - name: Check images pulled
      run: docker ps -a 
    - name: run command on libvirt container
      run: docker exec libvirt_disco cat /etc/os-release 
    - name: run yum update on centos8 
      run: docker exec libvirt_disco yum update -y
    - name: run script libvirt deps
      run: docker exec libvirt_disco yum install -y qemu-kvm qemu-img virt-manager libvirt python3-libvirt libvirt-client
    - name: run script libvirt deps
      run: docker exec libvirt_disco yum groupinstall -y virtualization-client virtualization-platform virtualization-tools

