name: Python package

on: [pull_request]

jobs:
  build:

#    runs-on: ubuntu-latest
#    strategy:
#      max-parallel: 4
#      matrix:
#        python-version: [2.7, 3.5, 3.6, 3.7]
#jobs:
#  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    #    - name: Install dependencies
#      run: |
#        yum install python2-pip python3-pip -y
#        #        python -m pip install --upgrade pip
#        pip3 install -r requirements.txt
#        pip3 install .[test]
#        pip3 install setuptools
#        pip3 install flake8
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#       # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
##    - name: Test with pytest
#      run: |
#        python3 setup.py test
#    - name: Build build fedora30
#      run: docker build . --file ./config/Dockerfiles/fedora30/Dockerfile --tag myfedora30:latest
    - name: Build build centos7
      run: docker build . --file ./centos7dockerfile --tag mycentos7:latest
    - name: RUn in backgrnd
      run: docker run mycentos7:latest -d
    - name: list all the containers
      run: docker ps -a

